### ISSUE TITLE
How to add other graphs?

### ISSUE THREAD

**Issue by niusj** [ldbc/ldbc_graphalytics#169]
hi,

I'm wondering if I can run benchmarks on other graphs not in available graphalytics datasets (in config-template/graphs or on https://graphalytics.org/datasets).

If yes, can you give me some instructions? I only found "benchmark.custom.graphs= # Select a subset of the graphs".

Thank you so much!

**Comment by amusaafir** [comment]
Hi,

Let's say you want to use a data set named `test-dataset`.

First, you'll need to make sure that you have a vertices (test-dataset.v) and edge (test-dataset.e) file of your graph, similar as the ones in the existing Graphalytics data sets. Put these in the directory of  `graphs.root-directory`. If you have some validation data, you can add these in `graphs.validation-directory`. Otherwise, turn validation off.

1. Copy an existing graph property file in `config/graphs/` and rename it to `test-dataset.properties`. Modify this file according to your graph properties and needs. Make sure to rename the property names (from the old graph you've copied) to your new graph name as well.

2. Edit `config/graph.properties`. In the `graph.names` property, add the name of your new graph along with the others. Also add an `include` and refer to your graph file, e.g.: `include = graphs/test-dataset.properties`

3. In `config/benchmarks/custom.properties`, add `test-dataset` to `benchmark.custom.graphs`. 

If this is clear enough, I'll put it in the Wiki.

**Comment by niusj** [comment]
Thank you so much! It's clear, and I'll try it.

**Comment by amusaafir** [comment]
If it doesn't work out, feel free to re-open this! 

The explanation has also been added to the Wiki:
https://github.com/ldbc/ldbc_graphalytics/wiki/Manual%3A-Using-your-own-data-sets
